Append file extension based on content-type
inlife/nexrender pull request #570
Opened 2021-03-11 11:02 UTC by danixeee

As the title says, if the asset file extension is not present, now it's being appended based on response header content-type for `http` and `https` protocols.

2021-03-11 11:29 UTC, ivansenic requested changes
@danixeee Small changes please.. Or let's discuss if there is something not clear.

2021-03-11 11:29 UTC, ivansenic commented on packages/nexrender-core/src/tasks/download.js
> +        asset.extension = mime.extension(databuf.type) || ''
You should not update extension to `''` if it can not be resolved, but rather leave it `undefined`..

2021-03-11 11:29 UTC, ivansenic commented on packages/nexrender-core/src/tasks/download.js
> +                    if (path.extname(path.basename(asset.dest)) === '') {
* this if should rather be `if (!asset.extension)`
* if extension is found you should also update the `asset.extension`, to replicate the data2buf behavior

2021-03-27 07:08 UTC, merged

2021-03-27 07:09 UTC, inlife commented
Thanks for the contribution!